# Generated by Django 3.2.9 on 2022-10-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='repeat_password',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
